title:            mcansky's
description:      Writings from Thomas Riboulet.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://mcansky.github.io
    external:     true
  - name:         Email
    url:          mailto:riboulet+blog@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/mcansky
    external:     true
pygments:         true
exclude:          ["bundler", "_drafts"]
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

